Repository Shakthichaithanya/todo, pull requests merged in 2023-11, with the labels that each got.

#2 Feature/adding basic logic
  build.gradle
  gradlew
  src/main/java/com/todo/app/TodoAppApplication.java
  src/main/java/com/todo/app/controller/TaskController.java
  src/main/java/com/todo/app/dto/TaskDTO.java
  src/main/java/com/todo/app/entity/Task.java
  src/main/java/com/todo/app/exception/GlobalException.java
  src/main/java/com/todo/app/exception/TasksNotCreatedException.java
  src/main/java/com/todo/app/info/ErrorInfo.java
  src/main/java/com/todo/app/info/ResponseInfo.java
  src/main/java/com/todo/app/repository/TaskRepository.java
  src/main/java/com/todo/app/service/TaskService.java
  src/main/java/com/todo/app/service/TaskServiceImpl.java
  src/main/resources/application.yaml
  src/test/java/com/todo/app/TodoAppApplicationTests.java
  src/test/java/com/todo/app/controller/TaskControllerTest.java
Labels: enhancement

#4 added displayname annotation to testcases
  src/test/java/com/todo/app/controller/TaskControllerTest.java
Labels: enhancement

#9 8 add java doc comments to test cases
  .github/workflows/gradle.yml
  src/test/java/com/todo/app/controller/TaskControllerTest.java
Labels: documentation

#13 Create README.md
  README.md
Labels: documentation

#15 delete task
  .github/workflows/gradle.yml
  src/main/java/com/todo/app/controller/TaskController.java
  src/main/java/com/todo/app/repository/TaskRepository.java
  src/main/java/com/todo/app/service/TaskService.java
  src/main/java/com/todo/app/service/TaskServiceImpl.java
  src/test/java/com/todo/app/controller/TaskControllerTest.java
Labels: enhancement, good first issue
